gitlab_domain: "gitlab.example.com"
gitlab_external_url: "https://{{ gitlab_domain }}/"

gitlab_omniauth_providers: ""
gitlab_object_store_connection: ""
gitlab_ldap_servers: ""
gitlab_smtp:
gitlab_registry_storage: ""
gitlab_upgrade_version: ""