- name: Check if GitLab Runner is already installed.
  ansible.builtin.stat: path=/usr/bin/gitlab-runner
  register: gitlab_runner_file

- name: Check if GitLab Runner repository is already installed.
  ansible.builtin.stat: path=/etc/apt/sources.list.d/runner_gitlab-runner.list
  register: gitlab_runner_repo

- name: Install GitLab Runner dependencies
  ansible.builtin.apt:
    state: present
    package:
      - curl
      - perl
  when: not gitlab_runner_file.stat.exists

- name: Download GitLab Runner repository installation script
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/script.deb.sh
    validate_certs: true
  when: not gitlab_runner_repo.stat.exists

- name: Install GitLab Runner repository.
  ansible.builtin.command: bash /tmp/script.deb.sh
  environment:
    EXTERNAL_URL: gitlab_external_url
  when: not gitlab_runner_repo.stat.exists

- name: Install GitLab Runner
  ansible.builtin.package:
    name: "gitlab-runner"
    state: latest
  async: 600
  poll: 5

- name: Copy GitLab Runner configuration file.
  ansible.builtin.template:
    src: config.toml.j2
    dest: /home/{{ ansible_user }}/runner-config-template.toml
