- import_tasks: certs.yml

- name: Check if GitLab is already installed.
  ansible.builtin.stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Check if GitLab repository is already installed.
  ansible.builtin.stat: path=/etc/apt/sources.list.d/gitlab_gitlab-ce.list
  register: gitlab_repo

- name: Install GitLab dependencies
  ansible.builtin.apt:
    state: present
    package:
      - curl
      - perl
  when: not gitlab_file.stat.exists

- name: Download GitLab repository installation script
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh
    validate_certs: true
  when: not gitlab_repo.stat.exists

- name: Install GitLab repository.
  ansible.builtin.command: bash /tmp/script.deb.sh
  environment:
    EXTERNAL_URL: "{{ gitlab_external_url }}"
  when: not gitlab_repo.stat.exists

- name: Install GitLab
  ansible.builtin.package:
    name: "gitlab-ce"
    state: present
  when: not gitlab_file.stat.exists

# - name: Upgrade GitLab to specific version
#   ansible.builtin.package:
#     name: "gitlab-ce={{ gitlab_upgrade_version }}"
#     state: present
#   notify: restart gitlab
#   when: gitlab_upgrade_version | length > 0
#   tags: gitlab-upgrade

- name: Copy GitLab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab